#!/bin/csh 
#======================================================
#SBATCH -J GRIDS_REFL
#SBATCH -o gridrefl.o%j
#SBATCH -e gridrefl.err
#SBATCH -n 1
#SBATCH -t 0:10:00 
#SBATCH -p batch
#SBATCH --ntasks-per-node=1
#======================================================

echo "BEGIN GRIDS_REFL"
date

export PATH=./:/bin:/scratch/software/intel/netcdf/bin:/scratch/software/miniconda3/bin:$PATH
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/scratch/software/intel/netcdf/lib:/scratch/software/intel/hdf5/lib:/scratch/software/intel/grib2/libpng/lib:/scratch/software/intel/grib2/zlib/lib:/scratch/software/miniconda3/lib:/usr/lib64

sleep 1

srun grid_refl_obs_gsi.exe dbzobs.nc 35 10 wrfinput_d01.ensmean  > grid_refl.output

echo "END GRIDS_REFL"

touch refl_done

date
exit 0
