#!/bin/bash

eventdate=${1-20210503}
eventnext=$(date -d "$eventdate 1 day" +%Y%m%d)

scriptdir=/scratch/ywang/NEWSVAR/news3dvar.2023/scripts

conffile=/scratch/ywang/NEWSVAR/news3dvar.2023/scripts/config23_hyb.yaml
rundir=/scratch/ywang/test_runs/hyb23
domain=${rundir}/${eventdate}.dom

${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}1700 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}1800 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}1900 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}2000 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}2100 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}2200 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventdate}2300 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventnext}0000 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventnext}0100 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventnext}0200 ${rundir}
${scriptdir}/runhr-rlt -r 7 -c ${conffile} -d ${domain} ${eventnext}0300 ${rundir}
